// LOCALHOST 
### GET 
http://localhost:8080/contacts 
### GET 
http://localhost:8080/contacts/6511cf3052d6c2c9181f300c
### GET 
http://localhost:8080/contacts/6511cf9152d6c2c9181f300d
### GET 
http://localhost:8080/contacts/6511cfb652d6c2c9181f300e
### GET 
http://localhost:8080/contacts/6511cfe252d6c2c9181f300f


### POST Create Contact 
POST https://cse341-personalnefipr.onrender.com/contacts HTTP/1.1
content-Type: application/json

{
    "firstName": "Nefi",
    "lastName": "Perez",
    "email": "nefipr@gmail.com",
    "favoriteColor": "purple",
    "birthday": "24/08/1999"
}

### PUT Update Contact 
PUT https://cse341-personalnefipr.onrender.com/contacts/6511cf3052d6c2c9181f300c HTTP/1.1
content-Type: application/json

{
    "firstName": "Pamela",
    "lastName": "Perez",
    "email": "pamepr12@gmail.com",
    "favoriteColor": "ligth pink",
    "birthday": "12/07/1997"
}

### DELETE Update Contact 
DELETE https://cse341-personalnefipr.onrender.com/contacts/651b39bfa99b7012c6ffa4ed HTTP/1.1

// PRODUCTION Deploy 
### GET
https://cse341-personalnefipr.onrender.com/contacts
### GET 
https://cse341-personalnefipr.onrender.com/contacts/6511cf3052d6c2c9181f300c
### GET 
https://cse341-personalnefipr.onrender.com/contacts/6511cf9152d6c2c9181f300d
### GET 
https://cse341-personalnefipr.onrender.com/contacts/6511cfb652d6c2c9181f300e
### GET 
https://cse341-personalnefipr.onrender.com/contacts/6511cfe252d6c2c9181f300f

### POST Create Contact 
POST https://cse341-personalnefipr.onrender.com/contacts HTTP/1.1
content-Type: application/json

{
    "firstName": "Nefi",
    "lastName": "Perez",
    "email": "nefipr@gmail.com",
    "favoriteColor": "purple",
    "birthday": "24/08/1999"
}

### PUT Update Contact 
PUT https://cse341-personalnefipr.onrender.com/contacts/651b39bfa99b7012c6ffa4ed HTTP/1.1
content-Type: application/json

{
    "firstName": "Pamela",
    "lastName": "Perez",
    "email": "pamepr12@gmail.com",
    "favoriteColor": "ligth pink",
    "birthday": "12/07/1997"
}

### DELETE Update Contact 
DELETE https://cse341-personalnefipr.onrender.com/contacts/651b39bfa99b7012c6ffa4ed HTTP/1.1