// LOCALHOST 
### GET 
http://localhost:8080/contacts 
### GET 
http://localhost:8080/contacts/6511cf3052d6c2c9181f300c
### GET 
http://localhost:8080/contacts/6511cf9152d6c2c9181f300d
### GET 
http://localhost:8080/contacts/6511cfb652d6c2c9181f300e
### GET 
http://localhost:8080/contacts/6511cfe252d6c2c9181f300f

// PRODUCTION Deploy 
# ### GET
# https://cse341-instructor.herokuapp.com/contacts 
# ### GET 
# https://cse341-instructor.herokuapp.com/contacts/
# ### GET 
# https://cse341-instructor.herokuapp.com/contacts/
# ### GET 
# https://cse341-instructor.herokuapp.com/contacts/